notifications:
  templates:
    # ?? ?? ?? D-7
    apply-d7:
      title: ${NOTIF_APPLY_D7_TITLE}
      body: ${NOTIF_APPLY_D7_BODY}
      button1-name: ${NOTIF_APPLY_D7_BTN1_NAME}
      button1-url: ${NOTIF_APPLY_D7_BTN1_URL}

    # ?? ?? ?? D-Day
    apply-dday:
      title: ${NOTIF_APPLY_DDAY_TITLE}
      body: ${NOTIF_APPLY_DDAY_BODY}
      button1-name: ${NOTIF_APPLY_DDAY_BTN1_NAME}
      button1-url: ${NOTIF_APPLY_DDAY_BTN1_URL}

    # ?? ??? ?? D-7
    doc-d7:
      title: ${NOTIF_DOC_D7_TITLE}
      body: ${NOTIF_DOC_D7_BODY}
      button1-name: ${NOTIF_DOC_D7_BTN1_NAME}
      button1-url: ${NOTIF_DOC_D7_BTN1_URL}

    # ?? ??? ?? D-Day
    doc-dday:
      title: ${NOTIF_DOC_DDAY_TITLE}
      body: ${NOTIF_DOC_DDAY_BODY}
      button1-name: ${NOTIF_DOC_DDAY_BTN1_NAME}
      button1-url: ${NOTIF_DOC_DDAY_BTN1_URL}
      button2-name: ${NOTIF_DOC_DDAY_BTN2_NAME}
      button2-url: ${APP_BASE_URL}

app:
  base-url: ${APP_BASE_URL}

external:
  mypage:
    base-url: ${MYPAGE_BASE_URL}
  kakao:
    base-url: ${KAKAO_BASE_URL}
    send-to-me-path: ${KAKAO_SEND_TO_ME_PATH}
